# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://username.github.com # or your custom domain name
title : UK Rasch Users Group

author :
  name : Chris Wheadon
  email : chris.wheadon@gmail.com
  github : cbwheadon
  twitter : raschuk
  feedbuder : raschuk

exclude: .rbenv-version
